- name: debug backend image
  ansible.builtin.debug:
    var: backend_image

- name: Run backend container
  community.docker.docker_container:
    name: backend
    image: "{{ backend_image }}"
    state: started
    restart_policy: always
    env: "{{ backend_env }}"
    ports:
      - "{{ backend_port }}:8080"
    volumes:
      - /opt/app/backend/data:/app/data
    pull: yes
    recreate: yes