apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
  labels:
    app: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      name: rabbit-mq
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      