FROM golang:1.25 AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./main.go

FROM alpine:latest
WORKDIR /app
COPY --from=build /src/app .
ENTRYPOINT ["./app"]
